<?php

namespace ContainerWy2tzYI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O8aJQUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._o8aJQU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._o8aJQU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\IngredientController::delete' => ['privates', '.service_locator.0x2__nR', 'get_ServiceLocator_0x2NRService', true],
            'App\\Controller\\IngredientController::edit' => ['privates', '.service_locator.0x2__nR', 'get_ServiceLocator_0x2NRService', true],
            'App\\Controller\\IngredientController::index' => ['privates', '.service_locator.ZVK9RHj', 'get_ServiceLocator_ZVK9RHjService', true],
            'App\\Controller\\IngredientController::new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\IngredientController:delete' => ['privates', '.service_locator.0x2__nR', 'get_ServiceLocator_0x2NRService', true],
            'App\\Controller\\IngredientController:edit' => ['privates', '.service_locator.0x2__nR', 'get_ServiceLocator_0x2NRService', true],
            'App\\Controller\\IngredientController:index' => ['privates', '.service_locator.ZVK9RHj', 'get_ServiceLocator_ZVK9RHjService', true],
            'App\\Controller\\IngredientController:new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\IngredientController::delete' => '?',
            'App\\Controller\\IngredientController::edit' => '?',
            'App\\Controller\\IngredientController::index' => '?',
            'App\\Controller\\IngredientController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\IngredientController:delete' => '?',
            'App\\Controller\\IngredientController:edit' => '?',
            'App\\Controller\\IngredientController:index' => '?',
            'App\\Controller\\IngredientController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
