<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFx93o7m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFx93o7m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFx93o7m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFx93o7m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFx93o7m\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fx93o7m',
    'container.build_id' => 'ca0035d6',
    'container.build_time' => 1703367816,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFx93o7m');
