<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1bPI2tV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1bPI2tV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1bPI2tV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1bPI2tV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1bPI2tV\App_KernelDevDebugContainer([
    'container.build_hash' => '1bPI2tV',
    'container.build_id' => 'eadea8c8',
    'container.build_time' => 1703369038,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1bPI2tV');
